export const CSS_CLASS_NAMES = {
  SHIFT_TO_TOP_CENTER: 'shift-sections-to-top-center',
  SHIFT_TO_CENTER: 'shift-sections-to-center',

  MEMORY_INFO: 'memory-info',
  SHOW: 'show',
  HIDE: 'hide',
  MOVED: 'moved',
  DISABLED: 'disabled',
  DIM: 'dim',
  VERY_DIM: 'so-dim',
  SHADES_ON_TOP: 'shades-on-top',
  OVERLAY_MESSAGE: 'overlay-message',
  FADE_OUT_LIGHT: 'fade-out-light',
  FADE_HIDE: 'fade-hide',
  ANSWER_BUTTON: 'answer-btn',
  CHECK_FLASH_MODE_ANSWER: 'check-flash-mode-answer',
  VOCAB_COMPLETE: 'vocabs-complete',
  FLASH_CARD_CORRECT: 'flash-correct-answer',
  ANSWER_MESSAGE: 'answer-message',
  MCQ_CORRECT_ANSWER: 'mcq-correct-answer',
  MCQ_WRONG_ANSWER: 'wrong-answer',
  SETTING_ERROR: 'setting-error',
};